### ISSUE TITLE
FewShotPrompting anhand eines künstliche Chatverlaufs für alle Hauptabfragen

### ISSUE THREAD

**Issue by GeroWeinkauf** [EinKnopfzu/Projektseminar-OR#10]

**Comment by angeluul** [comment]
Habe das testweise für SalesArgument, DescriptionLongShops und WorthKnowingShop separat zum standardmäßigen Verlauf implementiert. Ich teste das jetzt noch, aber ich war eigtl. vorsichtig bzgl. Abhängigkeiten usw. Das return von get_embedding.py ist jetzt allerdings inkonsistent, weil in den drei oben genannten Fällen kein String sondern ein Dataframe der drei höchsten Ähnlichkeiten übergeben wird, bestehend aus Inputdata und key.

**Comment by angeluul** [comment]
Für alle aktuellen Abfragen implementiert.
