### ISSUE TITLE
POST (/generate): Neue Definition der Anfrage und Rückantwort

### ISSUE THREAD

**Issue by DominikWeiss** [EinKnopfzu/Projektseminar-OR#2]
Anfrage:
- Parameter für GPT mit vom Frontend empfangen
- Modellwechsel (Angelo)

Antwort:
[
  {
     typ: "title",
     prompt: "asd",
     antwort: "...."
  },
  {...}
]
(mit besseren Namen)

**Comment by GeroWeinkauf** [comment]
Done:
Antowrt erfolgt wie folgt:

 [
{"typ" : key,
                            "prompt" : user_prompt,
                            "response" : response.choices[0].message['content']
                        },
...
]
