### ISSUE TITLE
Repromting: Umformulierung oder Verbesserung der LLM-Antwort

### ISSUE THREAD

**Issue by DominikWeiss** [EinKnopfzu/Projektseminar-OR#3]
Repromting ganz neue Route (Dominik)
"neu verfassen": easy -> optional string anpassen und dann anfrage an LLM 

Umformulieren eines aktuellen Textes: -> Haben wir dafür schon einen
(Das ist etwas komplexer als es wirkt mit dem LLM. Was die Prompts angeht, der neigt dazu da einfach das "eingefügte Wort" unzusammenhängend einzufügen)

**Comment by GeroWeinkauf** [comment]
soweit vorhanden, jetzt muss Angelo noch spezifizieren, was genau wir benötigen und wie es im Backend dann zusammengesetzt wird

**Comment by angeluul** [comment]
Mache noch eben Tests bzgl. #10 und dann mach ich hiermit weiter.
