### ISSUE TITLE
GET (/status) + Frontend

### ISSUE THREAD

**Issue by DominikWeiss** [EinKnopfzu/Projektseminar-OR#4]
Backend Status
Wir brauchen 3: Idle, Loading, error
[
  Vorabfrage1,
  ...
]

HTTP-Status im Frontend ausgeben (bei HTTP-Error: Fehler anzeigen) -> Fehler Info WICHTIG wegen dem zweitem LLM

**Comment by GeroWeinkauf** [comment]
Status Route aktualisiert: Format wie im Postman

{
        "Daten vorverarbeitet" : False,
        "Daten vorabgefragt": False,
        "Datenesel erstellt": False,
        "Hauptabfrage AmazonTitle": False,
        "Antwort AmazonTitle": False,
        "Hauptabfrage DescriptionLongShops": False,
        "Datenähnlichkeiten gestartet" : False,
        "Datenähnlichkeiten abgeschlossen" : False,
        "Antwort DescriptionLongShops": False,
        "Hauptabfrage SalesArguments": False,
        "Antwort SalesArguments": False,
        "Hauptabfrage AmazonBulletPoints": False,
        "Antwort AmazonBulletPoints": False,
        "Hauptabfrage WorthKnowingShop": False,
        "Antwort WorthKnowingShop": False,
        "Hauptabfrage MetaKeywordShop": False,
        "Antwort MetaKeywordShop": False,
        "Hauptabfrage Reprompt": False,
        "Antwort Reprompt": False
    }

Problemüberhang: Die Sortierung der Abfolge wird während der jsonify Prozesses Alphabetisch sortiert...

**Comment by DominikWeiss** [comment]
Evtl mit Reihenfolge als Präfix nummerieren ("01_Daten vorverarbeitet", "02_Daten vorabgefragt",...)?
