### ISSUE TITLE
Lenghtcheck Python implementieren

### ISSUE THREAD

**Issue by DominikWeiss** [EinKnopfzu/Projektseminar-OR#5]

**Comment by GeroWeinkauf** [comment]
Find ich nicht sinnvoll, könnte zu endlosschleifen oder semantischem Unfug führen

**Comment by EinKnopfzu** [comment]
Wir könnten einen Loopcounter implementieren und den als Abbruchsbedingung einfügen. 
So können wir die ewig schlaufe lösen.
Das Problem liegt ja darin, dass das LLM nicht verlässlich zählen kann. 
Wenn wir das hinbekommen würden, können wir da strotzdem nicht rechtfertigen es mit dem LLM zu machen: 
- Teuer
- Risiko, dass es doch nicht klappt
- Was passiert bei verändertem LLM -> Nicht unbedingt futureproof? 

-> Wenn die Abbruchsbedingung erfüllt ist -> Fehlerinfo ausgeben.

**Comment by angeluul** [comment]
Kopie ausm Git:

Um die HTML-Formatierung der Ausgabe (zu der Länge ähnlich wichtige Bedingung) einzuhalten habe ich in meinen Testskripts einen Loop integriert der 3mal versucht die gewünschte Struktur zu generieren. Nach dem dritten mal wird einfach die falsch formatierte dritte Ausgabe übergeben mit einer Meldung dazu. Bislang kommt das sehr selten vor. Ich würde das noch großzügig testen um zu sehen wie hoch die Wahrscheinlichkeit ist dass das passiert je Attribut. 

Außerdem hilft da aktuell wie ich die Chat Completions in die Prompts integriere. I.d.R. findet sich der Prompt jetzt im Systemprompt wieder, und das LLM bekommt folgenden "fake" Chatverlauf: 
Ich: Beispielinput 1 -> Beispieloutput 1, 
Beispielinput 2 -> Beispieloutput 2, 
Beispielinput 3 -> Beispieloutput 3, 
Input -> Ausgabe. 

Scheinbar hilft das auch erheblich in Sachen Länge und eliminiert die Notwendigkeit von Training für die getesteten Attribute.

**Comment by angeluul** [comment]
Für alle Abfragen implementiert (zumindest soweit Infos zu Textlänge je Attribut vorhanden sind).
